<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.quyq.gwsu</groupId>
        <artifactId>business-security</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>business-security-server</artifactId>


    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>business-security-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>business-headless-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>business-kit-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-database</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-cache</artifactId>
        </dependency>

        <dependency>
            <groupId>org.quyq.gwsu</groupId>
            <artifactId>common-ai</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>

        <dependency>
            <groupId>com.dingtalk.open</groupId>
            <artifactId>app-stream-client</artifactId>
            <version>${dingtalk.stream.version}</version>
        </dependency>

        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>alibaba-dingtalk-service-sdk</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>dingtalk</artifactId>
            <version>2.2.54</version>
        </dependency>


    </dependencies>

</project>
