server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    async:
      request-timeout: 300s
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  profiles:
    active: dev
  application:
    name: gwsu-application
  reactor:
    context-propagation: auto
  threads:
    virtual:
      enabled: true
  config:
    import:
      - classpath:database.yaml
      - classpath:redis.yaml
      - classpath:elasticsearch.yaml

# mybatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: org.quyq.gwsu.**.domain,org.quyq.gwsu.**.vo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-handlers-package: org.quyq.gwsu.common.database.typehandler

ratel:
  auth:
    # 登录超时
    timeout: 18000
    is-concurrent: true
    platform:
      three-platform:
        dingtalk:
          client-id: <assistant_remote_control_config:dingTalk.clientId>
          client-secret: <assistant_remote_control_config:dingTalk.clientSecret>
          # 生成token后以重定向的形式返回数据，重定向地址见redirect-url
          redirect: true
          # 和redirect配合使用
          redirect-url: <basic_url_config:viewBaseUrl>/sub-system/login
          properties:
            # 钉钉服务器回调本系统的回调地址
            redirect_uri: <basic_url_config:apiBaseUrl>/system/auth/callback/manager/dingtalk
  api-key:
    pepper: b4r7qJv0m2YwJ3r1rX3j0Qv8nJx9mJfY7W2nV0kP6sUe8dL1

  security:
    ignore-urls:
      - /system/auth/**
      - /kit/file/stream/*
    auth-allow-urls:
      - /modules/list
      - /system/workspace/**
  job:
    executor:
      # job 执行器是否支持glue模式
      glue-enabled: true
    admin:
      trigger-poolfast-max: 200
      trigger-pool-slow-max: 100
      schedule-batch-size: 100
      logretentiondays: 30


logging:
  level:
    org.springframework.context.support: ERROR
    org.quyq: DEBUG
    org.quyq.gwsu.kit.job: ERROR
